name: Do benchy stuff

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ 'labeled', 'synchronize' ]

jobs:
  bench:
    runs-on: ubuntu-latest
    environment: 'benchmark'
    steps:
      - name: Check if should run benchmarks?
        run: echo "should_run=${{ github.event_name == 'push' || github.event.label.name == 'benchmark' || contains(github.event.pull_request.labels.*.name, 'benchmark') }}" >> $GITHUB_ENV

      - name: Debug # TODO drop
        run: echo "${{ env.should_run }} | ${{ github.event_name }} | ${{ github.event.label.name }} | ${{ contains(github.event.pull_request.labels.*.name, 'benchmark') }}"

      - name: Checkout
        uses: actions/checkout@v1
        if: ${{ env.should_run }}

      - name: Run benchmarks
        run: "cp benchmarks.json ${{ github.sha }}.json" #TODO replace with sbt call
        if: ${{ env.should_run }}

      - name: Fetch benchmarks metadata
        run: curl https://raw.githubusercontent.com/lbialy/chimney-test-data/main/meta.json -o meta.json
        if: ${{ env.should_run }}

      - name: Get nope.js
        uses: actions/setup-node@v3
        if: ${{ env.should_run }}

      - name: Process current benchmarks results
        run: node process-benchmarks.mjs "$GITHUB_CONTEXT" "$(git describe --tags --always)"
        if: ${{ env.should_run }}
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Push benchmark file
        uses: dmnemec/copy_file_to_another_repo_action@main
        if: ${{ env.should_run }}
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: '${{ github.sha }}.json'
          destination_repo: 'lbialy/chimney-test-data'
          user_email: 'lukasz.marcin.bialy@gmail.com'
          user_name: 'Łukasz Biały'
          commit_message: 'Benchmarks for ${{ github.sha }} added.'

      - name: Push meta file
        uses: dmnemec/copy_file_to_another_repo_action@main
        if: ${{ env.should_run }}
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'meta.json'
          destination_repo: 'lbialy/chimney-test-data'
          user_email: 'lukasz.marcin.bialy@gmail.com'
          user_name: 'Łukasz Biały'
          commit_message: 'Meta update for ${{ github.sha }}'


