name: Publish benchmark results

on:
  workflow_run:
    workflows: ["Run benchmarks"]
    types:
      - completed

jobs:
  push-to-data-repo:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download artifact
        uses: actions/github-script@v6.3.3
        with:
          script: |
            var artifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "benchmark-results"
            })[0];
            var download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/benchmark-results.zip', Buffer.from(download.data));

      - run: unzip benchmark-results.zip

      - run: ls -hal # TODO drop debug

      - name: Push benchmark file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: '${{ github.sha }}.json'
          destination_repo: 'lbialy/chimney-test-data'
          user_email: 'lukasz.marcin.bialy@gmail.com'
          user_name: 'Łukasz Biały'
          commit_message: 'Benchmarks for ${{ github.sha }} added.'

      - name: Push meta file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'meta.json'
          destination_repo: 'lbialy/chimney-test-data'
          user_email: 'lukasz.marcin.bialy@gmail.com'
          user_name: 'Łukasz Biały'
          commit_message: 'Meta update for ${{ github.sha }}'